---
- hosts: all
  become: yes
  user: ubuntu
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        mode: 0755
    - name: Copy custom index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: restart nginx
      service:
        name: nginx
        state: restarted